/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 ./public/ADN.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'
import { useRef } from 'react'
import { useFrame } from '@react-three/fiber'
import { Html } from '@react-three/drei'

export function ADN(props) {
  const { nodes, materials } = useGLTF('/ADN.glb')
  const groupRef = useRef()

  useFrame(() => {
    if (groupRef.current) {
      groupRef.current.rotation.y += 0.01; 
  
    }
  });


  return (
    <>
    <group {...props} dispose={null} scale={0.5} ref={groupRef}>
      <mesh geometry={nodes.Cylinder_0.geometry} material={materials['_atom_09(quads)_3']} position={[-0.038, 0, -0.183]} scale={0.01} />
      <mesh geometry={nodes.Cylinder_1_1.geometry} material={materials['_atom_09(quads)_3']} position={[-0.038, 0, -0.183]} scale={0.01} />
      <mesh geometry={nodes.Cylinder_1_0.geometry} material={materials['_atom_09(quads)_2']} position={[-0.038, 0, -0.183]} scale={0.01} />
      <mesh geometry={nodes.Cylinder_1.geometry} material={materials['_atom_09(quads)_1']} position={[-0.038, 0, -0.183]} scale={0.01} />
      <mesh geometry={nodes.Cylinder_1_2.geometry} material={materials['_atom_09(quads)_2']} position={[-0.038, 0, -0.183]} scale={0.01} />
      <mesh geometry={nodes.Cylinder_3.geometry} material={materials['_atom_09(quads)_1']} position={[-0.038, 0, -0.183]} scale={0.01} />
      <mesh geometry={nodes.Cylinder_1_4.geometry} material={materials['_atom_09(quads)_2']} position={[-0.038, 0, -0.183]} scale={0.01} />
      <mesh geometry={nodes.Cylinder_5.geometry} material={materials['_atom_09(quads)_1']} position={[-0.038, 0, -0.183]} scale={0.01} />
      <mesh geometry={nodes.Cylinder_1_6.geometry} material={materials['_atom_09(quads)_2']} position={[-0.038, 0, -0.183]} scale={0.01} />
      <mesh geometry={nodes.Cylinder_7.geometry} material={materials['_atom_09(quads)_1']} position={[-0.038, 0, -0.183]} scale={0.01} />
      <mesh geometry={nodes.Cylinder_1_8.geometry} material={materials['_atom_09(quads)_2']} position={[-0.038, 0, -0.183]} scale={0.01} />
      <mesh geometry={nodes.Cylinder_9.geometry} material={materials['_atom_09(quads)_1']} position={[-0.038, 0, -0.183]} scale={0.01} />
      <mesh geometry={nodes.Cylinder_1_10.geometry} material={materials['_atom_09(quads)_2']} position={[-0.038, 0, -0.183]} scale={0.01} />
      <mesh geometry={nodes.Cylinder_11.geometry} material={materials['_atom_09(quads)_1']} position={[-0.038, 0, -0.183]} scale={0.01} />
      <mesh geometry={nodes.Cylinder_1_12.geometry} material={materials['_atom_09(quads)_2']} position={[-0.038, 0, -0.183]} scale={0.01} />
      <mesh geometry={nodes.Cylinder_13.geometry} material={materials['_atom_09(quads)_1']} position={[-0.038, 0, -0.183]} scale={0.01} />
      <mesh geometry={nodes.Cylinder_1_14.geometry} material={materials['_atom_09(quads)_2']} position={[-0.038, 0, -0.183]} scale={0.01} />
      <mesh geometry={nodes.Cylinder_15.geometry} material={materials['_atom_09(quads)_1']} position={[-0.038, 0, -0.183]} scale={0.01} />
      <mesh geometry={nodes.Cylinder_1_16.geometry} material={materials['_atom_09(quads)_2']} position={[-0.038, 0, -0.183]} scale={0.01} />
      <mesh geometry={nodes.Cylinder_17.geometry} material={materials['_atom_09(quads)_1']} position={[-0.038, 0, -0.183]} scale={0.01} />
      <mesh geometry={nodes.Cylinder_1_18.geometry} material={materials['_atom_09(quads)_2']} position={[-0.038, 0, -0.183]} scale={0.01} />
      <mesh geometry={nodes.Cylinder_19.geometry} material={materials['_atom_09(quads)_1']} position={[-0.038, 0, -0.183]} scale={0.01} />
      <mesh geometry={nodes.Cylinder_1_20.geometry} material={materials['_atom_09(quads)_2']} position={[-0.038, 0, -0.183]} scale={0.01} />
      <mesh geometry={nodes.Cylinder_21.geometry} material={materials['_atom_09(quads)_1']} position={[-0.038, 0, -0.183]} scale={0.01} />
      <mesh geometry={nodes.Cylinder_1_22.geometry} material={materials['_atom_09(quads)_2']} position={[-0.038, 0, -0.183]} scale={0.01} />
      <mesh geometry={nodes.Cylinder_23.geometry} material={materials['_atom_09(quads)_1']} position={[-0.038, 0, -0.183]} scale={0.01} />
      <mesh geometry={nodes.Cylinder_1_24.geometry} material={materials['_atom_09(quads)_2']} position={[-0.038, 0, -0.183]} scale={0.01} />
      <mesh geometry={nodes.Cylinder_25.geometry} material={materials['_atom_09(quads)_1']} position={[-0.038, 0, -0.183]} scale={0.01} />
      <mesh geometry={nodes.Cylinder_1_26.geometry} material={materials['_atom_09(quads)_2']} position={[-0.038, 0, -0.183]} scale={0.01} />
      <mesh geometry={nodes.Cylinder_27.geometry} material={materials['_atom_09(quads)_1']} position={[-0.038, 0, -0.183]} scale={0.01} />
      <mesh geometry={nodes.Cylinder_1_28.geometry} material={materials['_atom_09(quads)_2']} position={[-0.038, 0, -0.183]} scale={0.01} />
      <mesh geometry={nodes.Cylinder_29.geometry} material={materials['_atom_09(quads)_1']} position={[-0.038, 0, -0.183]} scale={0.01} />
      <mesh geometry={nodes.Cylinder_1_30.geometry} material={materials['_atom_09(quads)_2']} position={[-0.038, 0, -0.183]} scale={0.01} />
      <mesh geometry={nodes.Cylinder_31.geometry} material={materials['_atom_09(quads)_1']} position={[-0.038, 0, -0.183]} scale={0.01} />
      <mesh geometry={nodes.Cylinder_1_32.geometry} material={materials['_atom_09(quads)_2']} position={[-0.038, 0, -0.183]} scale={0.01} />
      <mesh geometry={nodes.Cylinder_33.geometry} material={materials['_atom_09(quads)_1']} position={[-0.038, 0, -0.183]} scale={0.01} />
      <mesh geometry={nodes.Cylinder_1_34.geometry} material={materials['_atom_09(quads)_2']} position={[-0.038, 0, -0.183]} scale={0.01} />
      <mesh geometry={nodes.Cylinder_35.geometry} material={materials['_atom_09(quads)_1']} position={[-0.038, 0, -0.183]} scale={0.01} />
    </group>

    <Html position={[ 8, 6, -5]}>
    <div  style={{ background: 'white', padding: '10px', borderRadius: '4px', fontSize: '12px', width:"290px", fontFamily:"Roboto Mono"}}>
    <div style={{ display: "flex", flexDirection: "column", alignItems: "center", justifyContent: "center" }}>
            <span style={{ fontSize:"15px", fontWeight:"bold", textAlign:"center", marginBottom:"5px"}}> what's a ADN sequence </span>
            <div style={{marginTop:"10px", marginBotom:"5px"}}>
            DNA (deoxyribonucleic acid) is the molecule that carries genetic instructions for all living organisms. It's made up of two 
            strands forming a double helix, with sequences of four bases (adenine, thymine, cytosine, and guanine) that encode the information 
            for building and maintaining cells. DNA determines an organism's traits and is passed from one generation to the next.
            </div>
            <div style={{ width: '250px', height: '200px', overflow: 'hidden', borderRadius:"5px", marginTop:"10px" }}>
               <img src="/AD.jpeg" alt="Rib" style={{ width: '100%', height: '100%', objectFit: 'cover' }} />
            </div>
            <div style={{marginTop:"10px"}}>
            

            </div>
            </div>
    </div>

    </Html>

    </>
  )
}

useGLTF.preload('/ADN.glb')
