/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 ./public/drone.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'
import { useRef } from 'react'
import { useFrame } from '@react-three/fiber'
import { Html } from '@react-three/drei'
export function Drone(props) {
  const { nodes, materials } = useGLTF('/drone.glb')

  const groupRef = useRef();

useFrame(() => {
  if (groupRef.current) {
    groupRef.current.rotation.y += 0.005; 

  }
});

  return (
    <>
    <group ref={groupRef} {...props} dispose={null} scale={3}  >
      <mesh geometry={nodes.Plane.geometry} material={nodes.Plane.material} position={[0.139, 0, -1.082]} rotation={[0, 0.862, 0]} scale={1.935} />
      <mesh geometry={nodes.hélice007.geometry} material={materials['helice 2']} position={[-0.292, 0.321, -0.844]} rotation={[-0.259, 0.575, 0.143]} scale={1.2} />
      <mesh geometry={nodes.hélice006.geometry} material={materials['helice 2']} position={[-0.065, 0.321, -1.049]} rotation={[-2.883, -0.575, -2.999]} scale={1.2} />
      <mesh geometry={nodes.hélice005.geometry} material={materials['helice 1']} position={[0.293, 0.321, -0.368]} rotation={[-2.765, 0.947, 2.831]} scale={1.2} />
      <mesh geometry={nodes.hélice004.geometry} material={materials['helice 1']} position={[0.088, 0.321, -0.595]} rotation={[-0.376, -0.947, -0.31]} scale={1.2} />
      <mesh geometry={nodes.hélice003.geometry} material={materials['helice 3']} position={[0.769, 0.321, -0.952]} rotation={[-2.883, -0.575, -2.999]} scale={1.2} />
      <mesh geometry={nodes.hélice002.geometry} material={materials['helice 3']} position={[0.542, 0.321, -0.748]} rotation={[-0.259, 0.575, 0.143]} scale={1.2} />
      <mesh geometry={nodes.hélice001.geometry} material={materials['helice 4']} position={[0.185, 0.321, -1.429]} rotation={[-0.376, -0.947, -0.31]} scale={1.2} />
      <mesh geometry={nodes.hélice.geometry} material={materials['helice 4']} position={[0.389, 0.321, -1.202]} rotation={[-2.765, 0.947, 2.831]} scale={1.2} />
      <mesh geometry={nodes['G-__564240'].geometry} material={materials.bateria} position={[1.243, 0.004, -0.39]} rotation={[0, -1.494, 0]} />
      <mesh geometry={nodes['G-__564231'].geometry} material={materials['Materia escura']} position={[1.25, 0.037, -0.401]} rotation={[0, -1.494, 0]} />
      <mesh geometry={nodes['G-__564222'].geometry} material={materials['102,102,102']} position={[1.25, 0.036, -0.401]} rotation={[0, -1.494, 0]} />
      <mesh geometry={nodes['G-__564204'].geometry} material={materials['Materia escura']} position={[1.203, 0.033, -0.39]} rotation={[0, -1.494, 0]} />
      <mesh geometry={nodes['G-__564186'].geometry} material={materials['Material.001']} position={[1.262, 0.047, -0.376]} rotation={[1.727, -0.012, 3.066]} />
      <mesh geometry={nodes['G-__564177'].geometry} material={materials['102,102,102']} position={[1.248, 0.045, -0.366]} rotation={[0.158, 0.076, -0.012]} />
      <mesh geometry={nodes['G-__564168'].geometry} material={materials['Materia escura']} position={[1.261, 0.034, -0.406]} rotation={[-Math.PI, 1.494, -2.985]} scale={[1.828, 2.184, 1.29]} />
      <mesh geometry={nodes['G-__564159'].geometry} material={materials['Materia escura']} position={[1.222, 0.046, -0.409]} rotation={[-Math.PI, 1.494, -2.985]} scale={1.29} />
      <mesh geometry={nodes['G-__564150'].geometry} material={materials['Materia escura']} position={[1.297, 0.046, -0.415]} rotation={[-Math.PI, 1.494, -2.985]} scale={1.29} />
      <mesh geometry={nodes['G-__564141'].geometry} material={materials['Materia escura']} position={[1.237, 0.055, -0.454]} rotation={[-Math.PI, 1.494, -2.985]} scale={[0.387, 1.29, 1.29]} />
      <mesh geometry={nodes['G-__564132'].geometry} material={materials['Materia escura']} position={[1.241, 0.046, -0.399]} rotation={[-Math.PI, 1.494, -2.985]} scale={[0.387, 1.29, 1.29]} />
      <group position={[1.337, 0.045, -0.382]} rotation={[-Math.PI, 1.494, -2.985]} scale={0.636}>
        <mesh geometry={nodes['G-__564114_1'].geometry} material={materials['102,102,102']} />
        <mesh geometry={nodes['G-__564114_2'].geometry} material={materials['Material.001']} />
        <mesh geometry={nodes['G-__564114_3'].geometry} material={materials['Materia escura']} />
      </group>
      <mesh geometry={nodes['G-__564105'].geometry} material={materials['Materia escura']} position={[1.175, 0.045, -0.37]} rotation={[0.158, 0.076, -0.012]} scale={0.636} />
      <mesh geometry={nodes['G-__564096'].geometry} material={materials['Materia escura']} position={[1.224, 0.033, -0.404]} rotation={[0, -1.494, 0]} />
      <mesh geometry={nodes['G-__564078'].geometry} material={materials['Material.001']} position={[1.222, 0.013, -0.357]} rotation={[-Math.PI, -0.077, -Math.PI / 2]} scale={1.493} />
      <mesh geometry={nodes['G-__564069'].geometry} material={materials['Material.001']} position={[1.226, 0.009, -0.358]} rotation={[Math.PI, -0.077, Math.PI]} scale={1.493} />
      <mesh geometry={nodes['G-__564060'].geometry} material={materials['Material.001']} position={[1.222, 0.009, -0.354]} rotation={[0, -1.494, 0]} scale={1.493} />
      <mesh geometry={nodes['G-__564042'].geometry} material={materials['Materia escura']} position={[1.198, 0.013, -0.378]} rotation={[0, -1.494, 0]} scale={1.821} />
      <mesh geometry={nodes['G-__564033'].geometry} material={materials['azul traco cor 0,0,255']} position={[1.213, 0.028, -0.364]} rotation={[0, -1.494, 0]} scale={[0.768, 0.906, 0.768]} />
      <mesh geometry={nodes['G-__564024'].geometry} material={materials['Material.001']} position={[1.273, 0.017, -0.346]} rotation={[0, 0.077, -Math.PI / 2]} scale={-1.209} />
      <mesh geometry={nodes['G-__564015'].geometry} material={materials['Material.001']} position={[1.27, 0.014, -0.345]} rotation={[0, 0.077, -Math.PI]} scale={-1.209} />
      <mesh geometry={nodes['G-__564006'].geometry} material={materials['Material.001']} position={[1.273, 0.014, -0.343]} rotation={[0, -1.494, -Math.PI]} scale={-1.209} />
      <mesh geometry={nodes['G-__563988'].geometry} material={materials['Materia escura']} position={[1.29, 0.017, -0.365]} rotation={[0, -1.494, -Math.PI]} scale={-1.475} />
      <mesh geometry={nodes['G-__563979'].geometry} material={materials['azul traco cor 0,0,255']} position={[1.299, 0.028, -0.371]} rotation={[0, -1.494, -Math.PI]} scale={[-0.768, -0.906, -0.768]} />
      <mesh geometry={nodes['G-__563970'].geometry} material={materials['Material.001']} position={[1.292, 0.013, -0.363]} rotation={[0, 0.077, -Math.PI / 2]} scale={-1.493} />
      <mesh geometry={nodes['G-__563961'].geometry} material={materials['Material.001']} position={[1.288, 0.009, -0.362]} rotation={[0, 0.077, -Math.PI]} scale={-1.493} />
      <mesh geometry={nodes['G-__563952'].geometry} material={materials['Material.001']} position={[1.292, 0.009, -0.359]} rotation={[0, -1.494, -Math.PI]} scale={-1.493} />
      <mesh geometry={nodes['G-__563934'].geometry} material={materials['Materia escura']} position={[1.312, 0.013, -0.386]} rotation={[0, -1.494, -Math.PI]} scale={-1.821} />
      <mesh geometry={nodes['G-__563925'].geometry} material={materials['azul traco cor 0,0,255']} position={[1.279, 0.029, -0.352]} rotation={[0, -1.494, -Math.PI]} scale={[-0.622, -0.734, -0.622]} />
      <mesh geometry={nodes['G-__563916'].geometry} material={materials['Material.001']} position={[1.243, 0.017, -0.343]} rotation={[-Math.PI, -0.077, -Math.PI / 2]} scale={1.209} />
      <mesh geometry={nodes['G-__563907'].geometry} material={materials['Material.001']} position={[1.246, 0.014, -0.344]} rotation={[Math.PI, -0.077, Math.PI]} scale={1.209} />
      <mesh geometry={nodes['G-__563898'].geometry} material={materials['Material.001']} position={[1.243, 0.014, -0.34]} rotation={[0, -1.494, 0]} scale={1.209} />
      <mesh geometry={nodes['G-__563880'].geometry} material={materials['Materia escura']} position={[1.224, 0.017, -0.36]} rotation={[0, -1.494, 0]} scale={1.475} />
      <mesh geometry={nodes['G-__563871'].geometry} material={materials['azul traco cor 0,0,255']} position={[1.236, 0.029, -0.349]} rotation={[0, -1.494, 0]} scale={[0.622, 0.734, 0.622]} />
      <mesh geometry={nodes['G-__563853'].geometry} material={materials['102,102,102']} position={[1.199, 0.033, -0.417]} rotation={[0, -1.494, 0]} />
      <group position={[1.211, 0.002, -0.428]} rotation={[0, -1.494, 0]}>
        <mesh geometry={nodes['G-__563844_1'].geometry} material={materials['azul traco cor 0,0,255']} />
        <mesh geometry={nodes['G-__563844_2'].geometry} material={materials['Material.001']} />
      </group>
      <group position={[1.166, 0.002, -0.479]} rotation={[0, -1.494, 0]}>
        <mesh geometry={nodes['G-__563835_1'].geometry} material={materials['102,102,102']} />
        <mesh geometry={nodes['G-__563835_2'].geometry} material={materials['azul traco cor 0,0,255']} />
        <mesh geometry={nodes['G-__563835_3'].geometry} material={materials['255,255,255']} />
        <mesh geometry={nodes['G-__563835_4'].geometry} material={materials['255,0,0']} />
      </group>
      <mesh geometry={nodes['G-__563817'].geometry} material={materials['helice 2']} position={[-0.182, 0.307, -0.93]} rotation={[0, 0.59, 0]} scale={1.044} />
      <mesh geometry={nodes['G-__563799'].geometry} material={materials['Materia escura']} position={[-0.214, 0.257, -0.957]} rotation={[Math.PI, 0.117, -Math.PI / 2]} scale={[0.6, 0.726, 0.6]} />
      <mesh geometry={nodes['G-__563790'].geometry} material={materials['Materia escura']} position={[-0.168, 0.257, -0.982]} rotation={[0, 1.454, Math.PI / 2]} scale={[0.6, 0.726, 0.6]} />
      <mesh geometry={nodes['G-__563781'].geometry} material={materials['Materia escura']} position={[-0.137, 0.207, -0.978]} rotation={[-Math.PI, 0.117, -Math.PI]} scale={1.2} />
      <mesh geometry={nodes['G-__563772'].geometry} material={materials['helice 1']} position={[0.207, 0.307, -0.478]} rotation={[-Math.PI, 0.981, -Math.PI]} scale={1.044} />
      <mesh geometry={nodes['G-__563754'].geometry} material={materials['Materia escura']} position={[0.18, 0.257, -0.446]} rotation={[-Math.PI, -1.454, -Math.PI / 2]} scale={[0.6, 0.726, 0.6]} />
      <mesh geometry={nodes['G-__563745'].geometry} material={materials['Materia escura']} position={[0.155, 0.257, -0.492]} rotation={[Math.PI, 0.117, -Math.PI / 2]} scale={[0.6, 0.726, 0.6]} />
      <mesh geometry={nodes['G-__563736'].geometry} material={materials['Materia escura']} position={[0.159, 0.207, -0.523]} rotation={[Math.PI, -1.454, Math.PI]} scale={1.2} />
      <mesh geometry={nodes['G-__563727'].geometry} material={materials['helice 3']} position={[0.659, 0.307, -0.867]} rotation={[Math.PI, -0.59, Math.PI]} scale={1.044} />
      <mesh geometry={nodes['G-__563709'].geometry} material={materials['Materia escura']} position={[0.691, 0.257, -0.839]} rotation={[0, -0.117, Math.PI / 2]} scale={[0.6, 0.726, 0.6]} />
      <mesh geometry={nodes['G-__563700'].geometry} material={materials['Materia escura']} position={[0.645, 0.257, -0.814]} rotation={[-Math.PI, -1.454, -Math.PI / 2]} scale={[0.6, 0.726, 0.6]} />
      <mesh geometry={nodes['G-__563691'].geometry} material={materials['Materia escura']} position={[0.614, 0.207, -0.818]} rotation={[0, -0.117, 0]} scale={1.2} />
      <mesh geometry={nodes['G-__563682'].geometry} material={materials['helice 4']} position={[0.27, 0.307, -1.319]} rotation={[0, -0.981, 0]} scale={1.044} />
      <mesh geometry={nodes['G-__563664'].geometry} material={materials['Materia escura']} position={[0.298, 0.257, -1.351]} rotation={[0, 1.454, Math.PI / 2]} scale={[0.6, 0.726, 0.6]} />
      <mesh geometry={nodes['G-__563655'].geometry} material={materials['Materia escura']} position={[0.323, 0.257, -1.305]} rotation={[0, -0.117, Math.PI / 2]} scale={[0.6, 0.726, 0.6]} />
      <mesh geometry={nodes['G-__563646'].geometry} material={materials['Materia escura']} position={[0.319, 0.207, -1.274]} rotation={[0, 1.454, 0]} scale={1.2} />
      <mesh geometry={nodes['G-__563637'].geometry} material={materials['farol quadrado']} position={[0.383, 0.209, -0.999]} rotation={[-Math.PI, 0.902, -Math.PI]} scale={1.2} />
      <mesh geometry={nodes['G-__563628'].geometry} material={materials['farol quadrado']} position={[0.138, 0.209, -1.042]} rotation={[Math.PI, -0.669, Math.PI]} scale={1.2} />
      <mesh geometry={nodes['G-__563619'].geometry} material={materials['farol quadrado']} position={[0.095, 0.209, -0.798]} rotation={[0, -0.902, 0]} scale={1.2} />
      <mesh geometry={nodes['G-__563610'].geometry} material={materials['farol quadrado']} position={[0.339, 0.209, -0.754]} rotation={[0, 0.669, 0]} scale={1.2} />
      <mesh geometry={nodes['G-__563601'].geometry} material={materials['azul traco cor 0,0,255']} position={[0.346, 0.239, -1.062]} rotation={[0, -0.902, 0]} scale={[1.2, 1.2, 0.84]} />
      <mesh geometry={nodes['G-__563592'].geometry} material={materials['azul traco cor 0,0,255']} position={[0.402, 0.239, -0.791]} rotation={[Math.PI, -0.669, Math.PI]} scale={[1.2, 1.2, 0.84]} />
      <mesh geometry={nodes['G-__563583'].geometry} material={materials['azul traco cor 0,0,255']} position={[0.132, 0.239, -0.735]} rotation={[-Math.PI, 0.902, -Math.PI]} scale={[1.2, 1.2, 0.84]} />
      <mesh geometry={nodes['G-__563574'].geometry} material={materials['azul traco cor 0,0,255']} position={[0.075, 0.239, -1.005]} rotation={[0, 0.669, 0]} scale={[1.2, 1.2, 0.84]} />
      <group position={[0.312, 0.085, -0.846]} rotation={[-Math.PI, 0.902, -Math.PI]} scale={0.924}>
        <mesh geometry={nodes['G-__563565_1'].geometry} material={materials['102,102,102']} />
        <mesh geometry={nodes['G-__563565_2'].geometry} material={materials['Materia escura']} />
      </group>
      <mesh geometry={nodes['G-__563556'].geometry} material={materials.led} position={[0.183, 0.133, -0.87]} rotation={[-1.996, -0.315, 2.171]} scale={0.8} />
      <mesh geometry={nodes['G-__563547'].geometry} material={materials.led} position={[0.176, 0.124, -0.879]} rotation={[-2.507, -0.567, 1.947]} scale={0.8} />
      <mesh geometry={nodes['G-__563538'].geometry} material={materials.led} position={[0.173, 0.11, -0.884]} rotation={[Math.PI, -0.669, Math.PI / 2]} scale={0.8} />
      <mesh geometry={nodes['G-__563529'].geometry} material={materials.led} position={[0.174, 0.095, -0.882]} rotation={[2.507, -0.567, 1.195]} scale={0.8} />
      <mesh geometry={nodes['G-__563520'].geometry} material={materials.led} position={[0.18, 0.084, -0.875]} rotation={[1.996, -0.315, 0.971]} scale={0.8} />
      <mesh geometry={nodes['G-__563511'].geometry} material={materials.led} position={[0.188, 0.078, -0.864]} rotation={[Math.PI / 2, 0, 0.902]} scale={0.8} />
      <mesh geometry={nodes['G-__563502'].geometry} material={materials.led} position={[0.197, 0.08, -0.852]} rotation={[1.145, 0.315, 0.971]} scale={0.8} />
      <mesh geometry={nodes['G-__563493'].geometry} material={materials.led} position={[0.205, 0.089, -0.843]} rotation={[0.634, 0.567, 1.195]} scale={0.8} />
      <mesh geometry={nodes['G-__563484'].geometry} material={materials.led} position={[0.208, 0.103, -0.839]} rotation={[0, 0.669, Math.PI / 2]} scale={0.8} />
      <mesh geometry={nodes['G-__563475'].geometry} material={materials.led} position={[0.207, 0.118, -0.841]} rotation={[-0.634, 0.567, 1.947]} scale={0.8} />
      <mesh geometry={nodes['G-__563466'].geometry} material={materials.led} position={[0.201, 0.129, -0.848]} rotation={[-1.145, 0.315, 2.171]} scale={0.8} />
      <mesh geometry={nodes['G-__563457'].geometry} material={materials.led} position={[0.193, 0.135, -0.859]} rotation={[-Math.PI / 2, 0, 2.239]} scale={0.8} />
      <mesh geometry={nodes['G-__563448'].geometry} material={materials['TG_vidro fume']} position={[0.208, 0.141, -0.832]} rotation={[-Math.PI / 2, 0, 2.239]} scale={1.2} />
      <group position={[0.338, 0.18, -0.884]} rotation={[-Math.PI / 2, 0, 2.239]} scale={0.924}>
        <mesh geometry={nodes['G-__563439_1'].geometry} material={materials['102,102,102']} />
        <mesh geometry={nodes['G-__563439_2'].geometry} material={materials['azul traco cor 0,0,255']} />
        <mesh geometry={nodes['G-__563439_3'].geometry} material={materials['255,255,255']} />
        <mesh geometry={nodes['G-__563439_4'].geometry} material={materials['Material.001']} />
        <mesh geometry={nodes['G-__563439_5'].geometry} material={materials['Materia escura']} />
      </group>
      <group position={[0.973, 0, -0.816]} rotation={[-Math.PI, 0.902, -Math.PI]} scale={1.2}>
        <mesh geometry={nodes['G-__563421_1'].geometry} material={materials['Material.001']} />
        <mesh geometry={nodes['G-__563421_2'].geometry} material={materials['102,102,102']} />
        <mesh geometry={nodes['G-__563421_3'].geometry} material={materials['255,255,255']} />
        <mesh geometry={nodes['G-__563421_4'].geometry} material={materials['azul traco cor 0,0,255']} />
        <mesh geometry={nodes['G-__563421_5'].geometry} material={materials['Materia escura']} />
      </group>
    </group>

    <Html position={[ 0, 0, 0]}>
    <div  style={{ background: 'white', padding: '10px', borderRadius: '4px', fontSize: '12px', width:"290px", fontFamily:"Roboto Mono"}}>
    <div style={{ display: "flex", flexDirection: "column", alignItems: "center", justifyContent: "center" }}>
            <span style={{ fontSize:"15px", fontWeight:"bold", textAlign:"center", marginBottom:"5px"}}>  </span>
            <div style={{marginTop:"10px", marginBotom:"5px"}}>
            The power-generating core of a drone is its propulsion system, which transforms electrical energy from the battery 
            into thrust to keep the drone airborne and maneuverable. Key components include the motors, propellers, electronic
             speed controllers (ESCs), and battery, all working together to convert energy into controlled movement. The process
              begins when electrical energy from the battery powers the motors, which spin the propellers at high speeds. 
            </div>
            <div style={{ width: '250px', height: '200px', overflow: 'hidden', borderRadius:"5px", marginTop:"10px" }}>
               <img src="/drone.png" alt="Rib" style={{ width: '100%', height: '100%', objectFit: 'cover' }} />
            </div>
            <div style={{marginTop:"10px"}}>
            

            </div>
            </div>
    </div>

    </Html>
    </>
  )
}

useGLTF.preload('/drone.glb')
