/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 ./public/GamingPerso.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'
import { Html } from '@react-three/drei'
import { useState } from 'react'


export function GamingPerso(props) {
  const { nodes, materials } = useGLTF('/GamingPerso.glb')
  const [humerus, setHumerus] = useState([15, -10,0]);
  const [ulna, setUlna] = useState([18, -20,0]);
  const [tete, setTete] = useState([-11, 20,0]);
  const [os, setOs] = useState([-20, -2,0]);
  const [fibula, setFibula] = useState([-10, 2,0]);
  const [spin, setSpin] = useState([-40, 2,0]);




  return (
    <group {...props} dispose={null} scale={0.09} position={[1, 0,0]}>
     
      <mesh geometry={nodes.humerus.geometry} material={materials.Bones___Vray} 
            position={humerus}

      />
      <mesh geometry={nodes.ulna.geometry} material={materials.Bones___Vray} 
                  position={ulna}
/>
      <mesh geometry={nodes.Radius.geometry} material={materials.Bones___Vray} 
      position={tete}/>
      <mesh geometry={nodes.sub01004.geometry} material={materials.Bones___Vray} 
      position={os}
      />
      <mesh geometry={nodes.FIBULA.geometry} material={materials.Bones___Vray} 
      position={fibula}
      />
      <mesh geometry={nodes.Tibia.geometry} material={materials.Bones___Vray}
      position={[10, -1,0]}
      />
      <mesh geometry={nodes.sub02_1.geometry} material={materials.Bones___Vray} 
      position={[-20, 15,0]}
      />
      <mesh geometry={nodes.sub02_1_1.geometry} material={materials.White___Vray} 
      position={[-20, 15,0]}
      />
      <mesh geometry={nodes.sub01_1001.geometry} material={materials.Bones___Vray} 
      position={[10, 2,0]}
      />
      <mesh geometry={nodes.sub01_1001_1.geometry} material={materials.White___Vray} 
            position={[10, 2,0]}

      />
      <mesh geometry={nodes.sub02_1001.geometry} material={materials.Bones___Vray} 
            position={[40, 21,0]}

      />
      <mesh geometry={nodes.sub02_1001_1.geometry} material={materials.White___Vray} 
            position={[40, 21,0]}

      />
      <mesh geometry={nodes.sub01_1010.geometry} material={materials.Bones___Vray} 
            position={spin}

      />
      <mesh geometry={nodes.sub01_1010_1.geometry} material={materials.White___Vray} 
      position={[-40, 2,0]}
      />
      <mesh geometry={nodes.sub01_1010_2.geometry} material={materials.Brown___Vray}
      position={[-40, 2,0]}
      />
 <Html position={humerus}
        

        >
        <input type="text" placeholder='entrer  la reponses' className='rounded-sm px-2' />    
        </Html>
        <Html position={ulna}
        

        >
        <input type="text" placeholder='entrer  la reponses' className='rounded-sm px-2' />    
        </Html>
        <Html position={tete}
        

        >
        <input type="text" placeholder='entrer  la reponses' className='rounded-sm px-2' />    
        </Html>
        <Html position={os} >

        </Html>

        <Html position={spin}>
        <input type="text" placeholder='entrer  la reponses' className='rounded-sm px-2' />    
        </Html>

        <Html position={fibula}>
     <span>fibula</span> 
        </Html>
      


    </group>
  )
}

useGLTF.preload('/GamingPerso.glb')
