/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 ./public/squel.glb 
*/

import React, { useEffect } from 'react';
import { useGLTF } from '@react-three/drei';
import { useState } from 'react';
import { useFrame } from '@react-three/fiber';
import { useRef } from 'react';
import { Html } from '@react-three/drei';
export function Squel(props) {
  const { nodes, materials } = useGLTF('/squel.glb')

  const groupRef = useRef(); 

  const [troncPosition, setTroncPosition] = useState([0, 0, 0]);
  const [plecsusPosition, setPlecsusPosition] = useState([0, 0, 0]);
   const [sub, setSub] = useState([0, 0, 0]);
   const [rotationY, setRotationY] = useState(0); // State to track rotation angle

   const [message, setMessage] = useState(null); // Holds message content and visibility
   const [message2, setMessage2] = useState(null); // Holds message content and visibility

   const [messagePosition, setMessagePosition] = useState([0, 0, 0]); // Controls message position

   
   
   useFrame(() => {
    if (groupRef.current) {
      groupRef.current.rotation.y += 0.005; // Adjust speed as needed
      setRotationY(groupRef.current.rotation.y); // Track the current rotation angle
    }
  });
  // Handle click for Tronc
  const handleTroncClick = () => {
    setTroncPosition((prev) => [prev[0] + 20, prev[1], prev[2]]);
    setMessage('What is Rib Cage?'); // Set the message text
    setMessage2(null)
// Adjust as needed
   
  }
  // Handle click for Plecsus
  const handlePlecsusClick = () => {
    setPlecsusPosition((prev) => [prev[0] - 25, prev[1], prev[2]]);
    setMessage2('what is a pelvic bones ?')
    setMessage(null)

  };
  const handlesub1 = () =>{
    setSub((prev) => [prev[0] + 20, prev[1], prev[2]]);
  }
  return (
    <>
    <group ref={groupRef} {...props} dispose={null}  scale={0.04}>
      <mesh geometry={nodes.Tronc_.geometry} material={materials.Bones___Vray} 
        position={troncPosition}
         
        onClick={handleTroncClick}      />
      <mesh geometry={nodes.plecsus.geometry} material={materials.Bones___Vray} 
      position={plecsusPosition}
      onClick={handlePlecsusClick}
      />
      <mesh geometry={nodes.sub01_1.geometry} material={materials.Bones___Vray} 
      
      />
      <mesh geometry={nodes.sub01_1_1.geometry} material={materials.White___Vray} />
      <mesh geometry={nodes.sub01_1_2.geometry} material={materials.Brown___Vray} 
      />
      <mesh geometry={nodes.sub01_1001.geometry} material={materials.Bones___Vray} 
      position={sub}
      onClick={handlesub1}/>
      <mesh geometry={nodes.sub01_1001_1.geometry} material={materials.White___Vray} />

      

        {/* Display the message */}
        {message && (
        <Html position={troncPosition}
        

        >
          <div style={{ background: 'white', padding: '10px', borderRadius: '4px', fontSize: '12px', width:"120px", fontFamily:"Roboto Mono"}}>
          <h1 style={{ fontSize: '13px' }}>{message}</h1>  
          </div>
        </Html>
      )}
       {/* Display the message */}
       {message2 && (
        <Html position={plecsusPosition}
        

        >
          <div style={{ background: 'white', padding: '10px', borderRadius: '4px', fontSize: '12px', width:"120px", fontFamily:"Roboto Mono"}}>
          <h1 style={{ fontSize: '13px' }}>{message2}</h1>  
          </div>
        </Html>
      )}
    </group>

    <Html position={[ 1, 1, -1]}
        

        >
          <div style={{ background: 'white', padding: '10px', borderRadius: '4px', fontSize: '12px', width:"290px", fontFamily:"Roboto Mono"}} >
          {message &&<div style={{ display: "flex", flexDirection: "column", alignItems: "center", justifyContent: "center" }}>
            <span style={{ fontSize:"15px", fontWeight:"bold", textAlign:"center", marginBottom:"5px"}}> {message}  </span>
            <div style={{marginTop:"10px", marginBotom:"5px"}}>
            The rib cage is the protective enclosure of the lungs, 
            heart and great vessels. It is made up of the ribs, part 
            of the vertebral column, and the sternum.
            </div>
            <div style={{ width: '200px', height: '200px', overflow: 'hidden', borderRadius:"5px", marginTop:"10px" }}>
               <img src="/rib.jpeg" alt="Rib" style={{ width: '100%', height: '100%', objectFit: 'cover' }} />
            </div>
            <div style={{marginTop:"10px"}}>
              <p><strong>Function</strong>:The rib cage protects the organs in the chest, like the heart and lungs.</p>

            </div>
            </div>}
            {message2 &&<div style={{ display: "flex", flexDirection: "column", alignItems: "center", justifyContent: "center" }}>
            <span style={{ fontSize:"15px", fontWeight:"bold", textAlign:"center", marginBottom:"5px"}}> {message2}  </span>
            <div style={{marginTop:"10px", marginBotom:"5px"}}>
            he pelvis (also known as the bony pelvis, or pelvic girdle) is the name given to the bones that make up the basin-shaped
             protective housing of the pelvic organs. They are the left and right ischium, ilium and pubis, as well as the coccyx and sacrum.
            </div>
            <div style={{ width: '200px', height: '200px', overflow: 'hidden', borderRadius:"5px", marginTop:"10px" }}>
               <img src="/pelv.jpeg" alt="Rib" style={{ width: '100%', height: '100%', objectFit: 'cover' }} />
            </div>
            <div style={{marginTop:"10px"}}>
              <p><strong>Function</strong>:he pelvis protects the pelvic organs, like the bladder, sex organs, and parts of the intestines, as well as providing support and balance to the rest of the skeletal system.</p>

            </div>
            </div>}
         
          </div>
        </Html>
    </>
  )
}

useGLTF.preload('/squel.glb');
